// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type AgentConnEvtT struct {
	ConnInfo struct {
		ConnId struct {
			Upid struct {
				Pid            uint32
				_              [4]byte
				StartTimeTicks uint64
			}
			Fd   int32
			_    [4]byte
			Tsid uint64
		}
		ReadBytes  uint64
		WriteBytes uint64
		Laddr      struct {
			In4 struct {
				SinFamily uint16
				SinPort   uint16
				SinAddr   struct{ S_addr uint32 }
				Pad       [8]uint8
			}
			_ [12]byte
		}
		Raddr struct {
			In4 struct {
				SinFamily uint16
				SinPort   uint16
				SinAddr   struct{ S_addr uint32 }
				Pad       [8]uint8
			}
			_ [12]byte
		}
		Protocol AgentTrafficProtocolT
		Role     AgentEndpointRoleT
	}
	ConnType AgentConnTypeT
	_        [4]byte
	Ts       uint64
}

type AgentConnTypeT uint32

const (
	AgentConnTypeTKConnect       AgentConnTypeT = 0
	AgentConnTypeTKClose         AgentConnTypeT = 1
	AgentConnTypeTKProtocolInfer AgentConnTypeT = 2
)

type AgentControlValueIndexT uint32

const (
	AgentControlValueIndexTKTargetTGIDIndex   AgentControlValueIndexT = 0
	AgentControlValueIndexTKStirlingTGIDIndex AgentControlValueIndexT = 1
	AgentControlValueIndexTKNumControlValues  AgentControlValueIndexT = 2
)

type AgentEndpointRoleT uint32

const (
	AgentEndpointRoleTKRoleClient  AgentEndpointRoleT = 1
	AgentEndpointRoleTKRoleServer  AgentEndpointRoleT = 2
	AgentEndpointRoleTKRoleUnknown AgentEndpointRoleT = 4
)

type AgentKernEvt struct {
	FuncName [16]int8
	Ts       uint64
	Seq      uint64
	Len      uint32
	Flags    uint8
	_        [3]byte
	ConnIdS  struct {
		TgidFd uint64
		Direct AgentTrafficDirectionT
		_      [4]byte
	}
	IsSample int32
	Step     AgentStepT
}

type AgentKernEvtData struct {
	Ke      AgentKernEvt
	BufSize uint32
	Msg     [30720]int8
	_       [4]byte
}

type AgentStepT uint32

const (
	AgentStepTStart       AgentStepT = 0
	AgentStepTSYSCALL_OUT AgentStepT = 1
	AgentStepTTCP_OUT     AgentStepT = 2
	AgentStepTIP_OUT      AgentStepT = 3
	AgentStepTQDISC_OUT   AgentStepT = 4
	AgentStepTDEV_OUT     AgentStepT = 5
	AgentStepTNIC_OUT     AgentStepT = 6
	AgentStepTNIC_IN      AgentStepT = 7
	AgentStepTDEV_IN      AgentStepT = 8
	AgentStepTIP_IN       AgentStepT = 9
	AgentStepTTCP_IN      AgentStepT = 10
	AgentStepTUSER_COPY   AgentStepT = 11
	AgentStepTSYSCALL_IN  AgentStepT = 12
	AgentStepTEnd         AgentStepT = 13
)

type AgentTrafficDirectionT uint32

const (
	AgentTrafficDirectionTKEgress  AgentTrafficDirectionT = 0
	AgentTrafficDirectionTKIngress AgentTrafficDirectionT = 1
)

type AgentTrafficProtocolT uint32

const (
	AgentTrafficProtocolTKProtocolUnset   AgentTrafficProtocolT = 0
	AgentTrafficProtocolTKProtocolUnknown AgentTrafficProtocolT = 1
	AgentTrafficProtocolTKProtocolHTTP    AgentTrafficProtocolT = 2
	AgentTrafficProtocolTKProtocolHTTP2   AgentTrafficProtocolT = 3
	AgentTrafficProtocolTKProtocolMySQL   AgentTrafficProtocolT = 4
	AgentTrafficProtocolTKProtocolCQL     AgentTrafficProtocolT = 5
	AgentTrafficProtocolTKProtocolPGSQL   AgentTrafficProtocolT = 6
	AgentTrafficProtocolTKProtocolDNS     AgentTrafficProtocolT = 7
	AgentTrafficProtocolTKProtocolRedis   AgentTrafficProtocolT = 8
	AgentTrafficProtocolTKProtocolNATS    AgentTrafficProtocolT = 9
	AgentTrafficProtocolTKProtocolMongo   AgentTrafficProtocolT = 10
	AgentTrafficProtocolTKProtocolKafka   AgentTrafficProtocolT = 11
	AgentTrafficProtocolTKProtocolMux     AgentTrafficProtocolT = 12
	AgentTrafficProtocolTKProtocolAMQP    AgentTrafficProtocolT = 13
	AgentTrafficProtocolTKNumProtocols    AgentTrafficProtocolT = 14
)

// LoadAgent returns the embedded CollectionSpec for Agent.
func LoadAgent() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AgentBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Agent: %w", err)
	}

	return spec, err
}

// LoadAgentObjects loads Agent and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*AgentObjects
//	*AgentPrograms
//	*AgentMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadAgentObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadAgent()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// AgentSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentSpecs struct {
	AgentProgramSpecs
	AgentMapSpecs
}

// AgentSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentProgramSpecs struct {
	AddReplyToBufferOrList            *ebpf.ProgramSpec `ebpf:"_addReplyToBufferOrList"`
	AddReplyToBufferOrListReturn      *ebpf.ProgramSpec `ebpf:"_addReplyToBufferOrListReturn"`
	WriteToClient                     *ebpf.ProgramSpec `ebpf:"_writeToClient"`
	WriteToClientReturn               *ebpf.ProgramSpec `ebpf:"_writeToClientReturn"`
	Accept4Entry                      *ebpf.ProgramSpec `ebpf:"accept4_entry"`
	CloseEntry                        *ebpf.ProgramSpec `ebpf:"close_entry"`
	ConnSocketRead                    *ebpf.ProgramSpec `ebpf:"connSocketRead"`
	ConnectEntry                      *ebpf.ProgramSpec `ebpf:"connect_entry"`
	DevHardStartXmit                  *ebpf.ProgramSpec `ebpf:"dev_hard_start_xmit"`
	DevQueueXmit                      *ebpf.ProgramSpec `ebpf:"dev_queue_xmit"`
	IpQueueXmit                       *ebpf.ProgramSpec `ebpf:"ip_queue_xmit"`
	IpRcvCore                         *ebpf.ProgramSpec `ebpf:"ip_rcv_core"`
	ProcessMultibulkBuffer            *ebpf.ProgramSpec `ebpf:"processMultibulkBuffer"`
	ProcessMultibulkBufferReturn      *ebpf.ProgramSpec `ebpf:"processMultibulkBufferReturn"`
	ReadEnter                         *ebpf.ProgramSpec `ebpf:"read_enter"`
	ReadvEnter                        *ebpf.ProgramSpec `ebpf:"readv_enter"`
	ReadvReturn                       *ebpf.ProgramSpec `ebpf:"readv_return"`
	RecvfromEnter                     *ebpf.ProgramSpec `ebpf:"recvfrom_enter"`
	RecvfromReturn                    *ebpf.ProgramSpec `ebpf:"recvfrom_return"`
	RecvmsgEnter                      *ebpf.ProgramSpec `ebpf:"recvmsg_enter"`
	SecuritySocketRecvmsgEnter        *ebpf.ProgramSpec `ebpf:"security_socket_recvmsg_enter"`
	SecuritySocketSendmsgEnter        *ebpf.ProgramSpec `ebpf:"security_socket_sendmsg_enter"`
	SendmsgEnter                      *ebpf.ProgramSpec `ebpf:"sendmsg_enter"`
	SkbCopyDatagramIter               *ebpf.ProgramSpec `ebpf:"skb_copy_datagram_iter"`
	SockAllocRet                      *ebpf.ProgramSpec `ebpf:"sock_alloc_ret"`
	SysAccept4Ret                     *ebpf.ProgramSpec `ebpf:"sys_accept4_ret"`
	TcpDestroySock                    *ebpf.ProgramSpec `ebpf:"tcp_destroy_sock"`
	TcpQueueRcv                       *ebpf.ProgramSpec `ebpf:"tcp_queue_rcv"`
	TcpRcvEstablished                 *ebpf.ProgramSpec `ebpf:"tcp_rcv_established"`
	TcpV4DoRcv                        *ebpf.ProgramSpec `ebpf:"tcp_v4_do_rcv"`
	TcpV4Rcv                          *ebpf.ProgramSpec `ebpf:"tcp_v4_rcv"`
	TracepointSyscallsSysEnterSendto  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysExitClose    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_close"`
	TracepointSyscallsSysExitConnect  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_connect"`
	TracepointSyscallsSysExitRead     *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_read"`
	TracepointSyscallsSysExitRecvfrom *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_recvfrom"`
	TracepointSyscallsSysExitRecvmsg  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_recvmsg"`
	TracepointSyscallsSysExitSendmsg  *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_sendmsg"`
	TracepointSyscallsSysExitSendto   *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_sendto"`
	TracepointSyscallsSysExitWrite    *ebpf.ProgramSpec `ebpf:"tracepoint__syscalls__sys_exit_write"`
	WriteEnter                        *ebpf.ProgramSpec `ebpf:"write_enter"`
	WritevEnter                       *ebpf.ProgramSpec `ebpf:"writev_enter"`
	WritevReturn                      *ebpf.ProgramSpec `ebpf:"writev_return"`
	XdpProxy                          *ebpf.ProgramSpec `ebpf:"xdp_proxy"`
}

// AgentMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type AgentMapSpecs struct {
	AddReplyToBufferOrListArgsMap       *ebpf.MapSpec `ebpf:"_addReplyToBufferOrList_args_map"`
	WriteToClientArgsMap                *ebpf.MapSpec `ebpf:"_writeToClient_args_map"`
	AcceptArgsMap                       *ebpf.MapSpec `ebpf:"accept_args_map"`
	CloseArgsMap                        *ebpf.MapSpec `ebpf:"close_args_map"`
	ConnEvtRb                           *ebpf.MapSpec `ebpf:"conn_evt_rb"`
	ConnInfoMap                         *ebpf.MapSpec `ebpf:"conn_info_map"`
	ConnectArgsMap                      *ebpf.MapSpec `ebpf:"connect_args_map"`
	ControlValues                       *ebpf.MapSpec `ebpf:"control_values"`
	CurRedisReq                         *ebpf.MapSpec `ebpf:"cur_redis_req"`
	ProcessMultibulkBufferReturnArgsMap *ebpf.MapSpec `ebpf:"processMultibulkBufferReturn_args_map"`
	Rb                                  *ebpf.MapSpec `ebpf:"rb"`
	ReadArgsMap                         *ebpf.MapSpec `ebpf:"read_args_map"`
	RedisClientSeq                      *ebpf.MapSpec `ebpf:"redis_client_seq"`
	RedisResponseSeq                    *ebpf.MapSpec `ebpf:"redis_response_seq"`
	SockKeyConnIdMap                    *ebpf.MapSpec `ebpf:"sock_key_conn_id_map"`
	SockRecmMap                         *ebpf.MapSpec `ebpf:"sock_recm_map"`
	SockXmitMap                         *ebpf.MapSpec `ebpf:"sock_xmit_map"`
	SyscallDataMap                      *ebpf.MapSpec `ebpf:"syscall_data_map"`
	SyscallRb                           *ebpf.MapSpec `ebpf:"syscall_rb"`
	WriteArgsMap                        *ebpf.MapSpec `ebpf:"write_args_map"`
}

// AgentObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentObjects struct {
	AgentPrograms
	AgentMaps
}

func (o *AgentObjects) Close() error {
	return _AgentClose(
		&o.AgentPrograms,
		&o.AgentMaps,
	)
}

// AgentMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentMaps struct {
	AddReplyToBufferOrListArgsMap       *ebpf.Map `ebpf:"_addReplyToBufferOrList_args_map"`
	WriteToClientArgsMap                *ebpf.Map `ebpf:"_writeToClient_args_map"`
	AcceptArgsMap                       *ebpf.Map `ebpf:"accept_args_map"`
	CloseArgsMap                        *ebpf.Map `ebpf:"close_args_map"`
	ConnEvtRb                           *ebpf.Map `ebpf:"conn_evt_rb"`
	ConnInfoMap                         *ebpf.Map `ebpf:"conn_info_map"`
	ConnectArgsMap                      *ebpf.Map `ebpf:"connect_args_map"`
	ControlValues                       *ebpf.Map `ebpf:"control_values"`
	CurRedisReq                         *ebpf.Map `ebpf:"cur_redis_req"`
	ProcessMultibulkBufferReturnArgsMap *ebpf.Map `ebpf:"processMultibulkBufferReturn_args_map"`
	Rb                                  *ebpf.Map `ebpf:"rb"`
	ReadArgsMap                         *ebpf.Map `ebpf:"read_args_map"`
	RedisClientSeq                      *ebpf.Map `ebpf:"redis_client_seq"`
	RedisResponseSeq                    *ebpf.Map `ebpf:"redis_response_seq"`
	SockKeyConnIdMap                    *ebpf.Map `ebpf:"sock_key_conn_id_map"`
	SockRecmMap                         *ebpf.Map `ebpf:"sock_recm_map"`
	SockXmitMap                         *ebpf.Map `ebpf:"sock_xmit_map"`
	SyscallDataMap                      *ebpf.Map `ebpf:"syscall_data_map"`
	SyscallRb                           *ebpf.Map `ebpf:"syscall_rb"`
	WriteArgsMap                        *ebpf.Map `ebpf:"write_args_map"`
}

func (m *AgentMaps) Close() error {
	return _AgentClose(
		m.AddReplyToBufferOrListArgsMap,
		m.WriteToClientArgsMap,
		m.AcceptArgsMap,
		m.CloseArgsMap,
		m.ConnEvtRb,
		m.ConnInfoMap,
		m.ConnectArgsMap,
		m.ControlValues,
		m.CurRedisReq,
		m.ProcessMultibulkBufferReturnArgsMap,
		m.Rb,
		m.ReadArgsMap,
		m.RedisClientSeq,
		m.RedisResponseSeq,
		m.SockKeyConnIdMap,
		m.SockRecmMap,
		m.SockXmitMap,
		m.SyscallDataMap,
		m.SyscallRb,
		m.WriteArgsMap,
	)
}

// AgentPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadAgentObjects or ebpf.CollectionSpec.LoadAndAssign.
type AgentPrograms struct {
	AddReplyToBufferOrList            *ebpf.Program `ebpf:"_addReplyToBufferOrList"`
	AddReplyToBufferOrListReturn      *ebpf.Program `ebpf:"_addReplyToBufferOrListReturn"`
	WriteToClient                     *ebpf.Program `ebpf:"_writeToClient"`
	WriteToClientReturn               *ebpf.Program `ebpf:"_writeToClientReturn"`
	Accept4Entry                      *ebpf.Program `ebpf:"accept4_entry"`
	CloseEntry                        *ebpf.Program `ebpf:"close_entry"`
	ConnSocketRead                    *ebpf.Program `ebpf:"connSocketRead"`
	ConnectEntry                      *ebpf.Program `ebpf:"connect_entry"`
	DevHardStartXmit                  *ebpf.Program `ebpf:"dev_hard_start_xmit"`
	DevQueueXmit                      *ebpf.Program `ebpf:"dev_queue_xmit"`
	IpQueueXmit                       *ebpf.Program `ebpf:"ip_queue_xmit"`
	IpRcvCore                         *ebpf.Program `ebpf:"ip_rcv_core"`
	ProcessMultibulkBuffer            *ebpf.Program `ebpf:"processMultibulkBuffer"`
	ProcessMultibulkBufferReturn      *ebpf.Program `ebpf:"processMultibulkBufferReturn"`
	ReadEnter                         *ebpf.Program `ebpf:"read_enter"`
	ReadvEnter                        *ebpf.Program `ebpf:"readv_enter"`
	ReadvReturn                       *ebpf.Program `ebpf:"readv_return"`
	RecvfromEnter                     *ebpf.Program `ebpf:"recvfrom_enter"`
	RecvfromReturn                    *ebpf.Program `ebpf:"recvfrom_return"`
	RecvmsgEnter                      *ebpf.Program `ebpf:"recvmsg_enter"`
	SecuritySocketRecvmsgEnter        *ebpf.Program `ebpf:"security_socket_recvmsg_enter"`
	SecuritySocketSendmsgEnter        *ebpf.Program `ebpf:"security_socket_sendmsg_enter"`
	SendmsgEnter                      *ebpf.Program `ebpf:"sendmsg_enter"`
	SkbCopyDatagramIter               *ebpf.Program `ebpf:"skb_copy_datagram_iter"`
	SockAllocRet                      *ebpf.Program `ebpf:"sock_alloc_ret"`
	SysAccept4Ret                     *ebpf.Program `ebpf:"sys_accept4_ret"`
	TcpDestroySock                    *ebpf.Program `ebpf:"tcp_destroy_sock"`
	TcpQueueRcv                       *ebpf.Program `ebpf:"tcp_queue_rcv"`
	TcpRcvEstablished                 *ebpf.Program `ebpf:"tcp_rcv_established"`
	TcpV4DoRcv                        *ebpf.Program `ebpf:"tcp_v4_do_rcv"`
	TcpV4Rcv                          *ebpf.Program `ebpf:"tcp_v4_rcv"`
	TracepointSyscallsSysEnterSendto  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_enter_sendto"`
	TracepointSyscallsSysExitClose    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_close"`
	TracepointSyscallsSysExitConnect  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_connect"`
	TracepointSyscallsSysExitRead     *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_read"`
	TracepointSyscallsSysExitRecvfrom *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_recvfrom"`
	TracepointSyscallsSysExitRecvmsg  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_recvmsg"`
	TracepointSyscallsSysExitSendmsg  *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_sendmsg"`
	TracepointSyscallsSysExitSendto   *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_sendto"`
	TracepointSyscallsSysExitWrite    *ebpf.Program `ebpf:"tracepoint__syscalls__sys_exit_write"`
	WriteEnter                        *ebpf.Program `ebpf:"write_enter"`
	WritevEnter                       *ebpf.Program `ebpf:"writev_enter"`
	WritevReturn                      *ebpf.Program `ebpf:"writev_return"`
	XdpProxy                          *ebpf.Program `ebpf:"xdp_proxy"`
}

func (p *AgentPrograms) Close() error {
	return _AgentClose(
		p.AddReplyToBufferOrList,
		p.AddReplyToBufferOrListReturn,
		p.WriteToClient,
		p.WriteToClientReturn,
		p.Accept4Entry,
		p.CloseEntry,
		p.ConnSocketRead,
		p.ConnectEntry,
		p.DevHardStartXmit,
		p.DevQueueXmit,
		p.IpQueueXmit,
		p.IpRcvCore,
		p.ProcessMultibulkBuffer,
		p.ProcessMultibulkBufferReturn,
		p.ReadEnter,
		p.ReadvEnter,
		p.ReadvReturn,
		p.RecvfromEnter,
		p.RecvfromReturn,
		p.RecvmsgEnter,
		p.SecuritySocketRecvmsgEnter,
		p.SecuritySocketSendmsgEnter,
		p.SendmsgEnter,
		p.SkbCopyDatagramIter,
		p.SockAllocRet,
		p.SysAccept4Ret,
		p.TcpDestroySock,
		p.TcpQueueRcv,
		p.TcpRcvEstablished,
		p.TcpV4DoRcv,
		p.TcpV4Rcv,
		p.TracepointSyscallsSysEnterSendto,
		p.TracepointSyscallsSysExitClose,
		p.TracepointSyscallsSysExitConnect,
		p.TracepointSyscallsSysExitRead,
		p.TracepointSyscallsSysExitRecvfrom,
		p.TracepointSyscallsSysExitRecvmsg,
		p.TracepointSyscallsSysExitSendmsg,
		p.TracepointSyscallsSysExitSendto,
		p.TracepointSyscallsSysExitWrite,
		p.WriteEnter,
		p.WritevEnter,
		p.WritevReturn,
		p.XdpProxy,
	)
}

func _AgentClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed agent_x86_bpfel.o
var _AgentBytes []byte
