// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type IpvsEntryInfoT struct {
	StartNs uint64
	ConnPtr uint64
	SkbPtr  uint64
}

// LoadIpvs returns the embedded CollectionSpec for Ipvs.
func LoadIpvs() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_IpvsBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Ipvs: %w", err)
	}

	return spec, err
}

// LoadIpvsObjects loads Ipvs and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*IpvsObjects
//	*IpvsPrograms
//	*IpvsMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadIpvsObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadIpvs()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// IpvsSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IpvsSpecs struct {
	IpvsProgramSpecs
	IpvsMapSpecs
}

// IpvsSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IpvsProgramSpecs struct {
	KprobeIpVsConnInGet     *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_conn_in_get"`
	KprobeIpVsConnNew       *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_conn_new"`
	KprobeIpVsConnOutGet    *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_conn_out_get"`
	KprobeIpVsConnPut       *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_conn_put"`
	KprobeIpVsDrXmit        *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_dr_xmit"`
	KprobeIpVsNatXmit       *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_nat_xmit"`
	KprobeIpVsSchedule      *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_schedule"`
	KprobeIpVsTunnelXmit    *ebpf.ProgramSpec `ebpf:"kprobe_ip_vs_tunnel_xmit"`
	KretprobeIpVsConnInGet  *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_conn_in_get"`
	KretprobeIpVsConnNew    *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_conn_new"`
	KretprobeIpVsConnOutGet *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_conn_out_get"`
	KretprobeIpVsConnPut    *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_conn_put"`
	KretprobeIpVsDrXmit     *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_dr_xmit"`
	KretprobeIpVsNatXmit    *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_nat_xmit"`
	KretprobeIpVsSchedule   *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_schedule"`
	KretprobeIpVsTunnelXmit *ebpf.ProgramSpec `ebpf:"kretprobe_ip_vs_tunnel_xmit"`
}

// IpvsMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type IpvsMapSpecs struct {
	IpvsEntryMap   *ebpf.MapSpec `ebpf:"ipvs_entry_map"`
	IpvsEvents     *ebpf.MapSpec `ebpf:"ipvs_events"`
	IpvsSkbConnMap *ebpf.MapSpec `ebpf:"ipvs_skb_conn_map"`
}

// IpvsObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadIpvsObjects or ebpf.CollectionSpec.LoadAndAssign.
type IpvsObjects struct {
	IpvsPrograms
	IpvsMaps
}

func (o *IpvsObjects) Close() error {
	return _IpvsClose(
		&o.IpvsPrograms,
		&o.IpvsMaps,
	)
}

// IpvsMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadIpvsObjects or ebpf.CollectionSpec.LoadAndAssign.
type IpvsMaps struct {
	IpvsEntryMap   *ebpf.Map `ebpf:"ipvs_entry_map"`
	IpvsEvents     *ebpf.Map `ebpf:"ipvs_events"`
	IpvsSkbConnMap *ebpf.Map `ebpf:"ipvs_skb_conn_map"`
}

func (m *IpvsMaps) Close() error {
	return _IpvsClose(
		m.IpvsEntryMap,
		m.IpvsEvents,
		m.IpvsSkbConnMap,
	)
}

// IpvsPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadIpvsObjects or ebpf.CollectionSpec.LoadAndAssign.
type IpvsPrograms struct {
	KprobeIpVsConnInGet     *ebpf.Program `ebpf:"kprobe_ip_vs_conn_in_get"`
	KprobeIpVsConnNew       *ebpf.Program `ebpf:"kprobe_ip_vs_conn_new"`
	KprobeIpVsConnOutGet    *ebpf.Program `ebpf:"kprobe_ip_vs_conn_out_get"`
	KprobeIpVsConnPut       *ebpf.Program `ebpf:"kprobe_ip_vs_conn_put"`
	KprobeIpVsDrXmit        *ebpf.Program `ebpf:"kprobe_ip_vs_dr_xmit"`
	KprobeIpVsNatXmit       *ebpf.Program `ebpf:"kprobe_ip_vs_nat_xmit"`
	KprobeIpVsSchedule      *ebpf.Program `ebpf:"kprobe_ip_vs_schedule"`
	KprobeIpVsTunnelXmit    *ebpf.Program `ebpf:"kprobe_ip_vs_tunnel_xmit"`
	KretprobeIpVsConnInGet  *ebpf.Program `ebpf:"kretprobe_ip_vs_conn_in_get"`
	KretprobeIpVsConnNew    *ebpf.Program `ebpf:"kretprobe_ip_vs_conn_new"`
	KretprobeIpVsConnOutGet *ebpf.Program `ebpf:"kretprobe_ip_vs_conn_out_get"`
	KretprobeIpVsConnPut    *ebpf.Program `ebpf:"kretprobe_ip_vs_conn_put"`
	KretprobeIpVsDrXmit     *ebpf.Program `ebpf:"kretprobe_ip_vs_dr_xmit"`
	KretprobeIpVsNatXmit    *ebpf.Program `ebpf:"kretprobe_ip_vs_nat_xmit"`
	KretprobeIpVsSchedule   *ebpf.Program `ebpf:"kretprobe_ip_vs_schedule"`
	KretprobeIpVsTunnelXmit *ebpf.Program `ebpf:"kretprobe_ip_vs_tunnel_xmit"`
}

func (p *IpvsPrograms) Close() error {
	return _IpvsClose(
		p.KprobeIpVsConnInGet,
		p.KprobeIpVsConnNew,
		p.KprobeIpVsConnOutGet,
		p.KprobeIpVsConnPut,
		p.KprobeIpVsDrXmit,
		p.KprobeIpVsNatXmit,
		p.KprobeIpVsSchedule,
		p.KprobeIpVsTunnelXmit,
		p.KretprobeIpVsConnInGet,
		p.KretprobeIpVsConnNew,
		p.KretprobeIpVsConnOutGet,
		p.KretprobeIpVsConnPut,
		p.KretprobeIpVsDrXmit,
		p.KretprobeIpVsNatXmit,
		p.KretprobeIpVsSchedule,
		p.KretprobeIpVsTunnelXmit,
	)
}

func _IpvsClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ipvs_arm64_bpfel.o
var _IpvsBytes []byte
